name: Sync All Branches to GitFlic

on:
  push:
    # Запуск при пуше в любую ветку и любой тег
    branches:
      - '**'
    tags:
      - '**'

jobs:
  gitflic-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Скачиваем всю историю всех веток

      - name: Push to GitFlic
        run: |
          git remote add gitflic https://${{ github.actor }}:${{ secrets.GITFLIC_TOKEN }}@gitflic.ru/${{ github.repository }}.git
          git push --force --all gitflic
          git push --force --tags gitflic
