name: Sync to GitFlic

on:
  push:
    # Убираем ограничение на ветку main, чтобы синхронизировалось ВСЁ
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch: # Оставляем возможность запустить вручную

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitFlic
        env:
          GITFLIC_TOKEN: ${{ secrets.GITFLIC_TOKEN }}
        run: |
          # Используем проверенный логин oauth2
          # Убрал /project/, так как это веб-путь, а не git-путь
          GITFLIC_REPO="https://oauth2:${GITFLIC_TOKEN}@gitflic.ru/fallendimmetrius/validate.git"
          
          git remote add gitflic $GITFLIC_REPO
          # --mirror синхронизирует абсолютно всё: все ветки и все теги за один раз
          git push --mirror --force gitflic
