name: Sync to GitFlic

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  workflow_dispatch: # Позволяет запустить синхронизацию вручную кнопкой

jobs:
  gitflic-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Важно для скачивания всей истории коммитов

      - name: Push to GitFlic
        run: |
          git remote remove gitflic || true
          
          # Пробуем передать токен как пароль к логину fallendimmetrius
          # Если это не сработает, попробуйте заменить fallendimmetrius на слово token
          git remote add gitflic https://fallendimmetrius:${{ secrets.GITFLIC_TOKEN }}@gitflic.ru/fallendimmetrius/validate.git
          
          # Добавим флаг, который иногда помогает при странных редиректах
          git config http.followRedirects true
          
          git push --force --all gitflic
          git push --force --tags gitflic
